"""initial

Revision ID: e97fe577937c
Revises: 
Create Date: 2024-01-29 12:50:27.893316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97fe577937c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_pairs',
    sa.Column('token', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(precision=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token', 'currency')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency_pairs')
    # ### end Alembic commands ###
