app:
  environment: "${APP_ENVIRONMENT}"
  name: "${APP_NAME}"

fastapi:
  prefix_v1: "/api/v1"

postgres:
  dsn : "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}"